### ISSUE TITLE
Glossary of terms

### ISSUE THREAD

**Issue by abankston-policy** [JMMaok/postdoc#21] opened 2021-05-01 22:22 UTC
https://docs.google.com/spreadsheets/d/1F7-cnP_pN1n7GV_AeOpt4EtPJ91OaUDujrmDVBdYyfc/edit#gid=1881037537 (second tab)

**Comment by JMMaok** [comment] 2021-05-05 20:28
Duplicate of #19

**Comment by JMMaok** [comment] 2021-05-05 20:29
Thank you, Adriana! I am moving this to the category Supplementary Material (issue #19)

**Closed by JMMaok** 2021-05-05 20:28 UTC
